### ISSUE TITLE
Problem about training the model

### ISSUE THREAD

**Issue by maple1217** [kundan2510/pixelCNN#1]
Thanks for your sharing about the implementation of this model.
However, when I try to train the model ("mnist_gen.py"), it will stop at the line "valid_fn = theano.function([X, X_r], cost)" and no response.
Do you know the problem?
Thank you!

**Comment by kundan2510** [comment]
Sometimes, compiling the model takes time. This time is even more if model has larger number of ops. Can you see if this problem goes away when number of pixelcnn layers is low say either 2 or 3.

You can do this by changing num_layers here: https://github.com/kundan2510/pixelCNN/blob/master/mnist_gen.py#L43

**Comment by maple1217** [comment]
Thanks for your reply.
When I decrease the number of layers to 3, the problem goes away.

I have another question about the vertical stacks and horizontal stacks. I haven't figure out how this can remove the blind spot. Could you please explain it simply?

**Comment by kundan2510** [comment]
@maple1217 I'll try to write something up with clear visualizations. For now, you can think of vertical stack having filters 3x3 have zero masks on its last row, e.g. upper 2x3 part is active. Now, its receptive field grows rectangularly in the same row (even towards the right!) and above it. To maintain causal convolution, i-row of the vertical stack is used only in the i+1-th row of horizontal stack. Hence, the causality in convolution is maintained and receptive rightward growth of receptive field in a row above removes the blind spot.

I am closing this issue for now.
